In [1]:
# Q1
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [2]:
# Q2
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 

In [17]:
import numpy as np

# try with just (2,2)
a = np.array([[1,2],[3,4]])    # Create a rank 2 array
print(a.shape)                     # Prints "(2, 3)"

b = np.array([[1,2],[3,4]])   
print(b.shape)        

op1 = l2_dist(a.T, b.T)
print(op1)

op2 = l2_dist(np.reshape(a, (2 * 2)), np.reshape(b, (2 * 2, 1)))
print(op2)

op3 = l2_dist(a, b)
print(op3)

op4 = l2_dist(np.reshape(a, (2 * 2)), np.reshape(b, (2 * 2)))
print(op4)

(2, 2)
(2, 2)
0.0
6.324555320336759
0.0
0.0


In [24]:
# Q3
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)

print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

# a4.ndim() == 1 # error
a5.shape == a1.shape # True
# a1.shape == a2.shape # false
# a3.shape == a4.shape # false

[0.08773372 0.8254211  0.64954951 0.27305675]
[[0.55869804]
 [0.88574898]
 [0.28461037]
 [0.16361181]]
[[1 2 3 4]]
[1 2 3]
[1. 2. 3. 4.]


True

In [25]:
# Q4
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [34]:
# Q5
r = np.array([
    [0,1,2,3,4,5],
    [6,7,8,9,10,11],
    [12,13,14,15,16,17],
    [18,19,20,21,22,23],
    [24,25,26,27,28,29],
    [30,31,32,33,34,35]
])

print(r)

# print('\n')
# print(r[[2,3],[2,3]])

# print('\n')
# print(r[[2,4],[2,4]])

# print('\n')
# print(r[2:3,2:3])

print('\n')
print(r[2:4,2:4])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[[14 15]
 [20 21]]


In [39]:
# Q6
import re 
s = 'ACBCAC'

# op1 = re.findall('[^A]C', s)
# print(op1)

# op2 = re.findall('^[AC]', s)
# print(op2)

op3 = re.findall('^AC', s)
print(op3)

# op4 = re.findall('AC', s)
# print(op4)

['AC']


In [41]:
# Q7
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
L

5

In [44]:
# Q8
text = """
Office of Research Administration: (734) 647-6333 | 4325 North Quad
Office of Budget and Financial Administration: (734) 647-8044 | 309 Maynard, Suite 205
Health Informatics Program: (734) 763-2285 | 333 Maynard, Suite 500
Office of the Dean: (734) 647-3576 | 4322 North Quad
UMSI Engagement Center: (734) 763-1251 | 777 North University
Faculty Adminstrative Support Staff: (734) 764-9376 | 4322 North Quad
"""
op1 = re.findall('[(]\d{3}[)]\d{3}[-]\d{4}', text)
print(op1)

op2 = re.findall('\d{3}\s\d{3}[-]\d{4}', text)
print(op2)

op3 = re.findall('\d{3}[-]\d{3}[-]\d{4}', text)
print(op3)

op4 = re.findall('[(]\d{3}[)]\s\d{3}[-]\d{4}', text)
print(op4)

[]
[]
[]
['(734) 647-6333', '(734) 647-8044', '(734) 763-2285', '(734) 647-3576', '(734) 763-1251', '(734) 764-9376']


In [45]:
# Q9
text = 'I refer to https://google.com and I never refer http://www.baidu.com if I have to search anything'

op1 = re.findall('(?<=https:\/\/)([A-Za-z0-9]*)', text)
print(op1)

op2 = re.findall('(?<=https:\/\/)([.]*)', text)
print(op2)

op3 = re.findall('(?<=https:\/\/)([A-Za-z0-9.]*)', text)
print(op3)

op4 = re.findall('(?<=[https]:\/\/)([A-Za-z0-9.]*)', text)
print(op4)

['google']
['']
['google.com']
['google.com', 'www.baidu.com']


In [50]:
# Q10
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
pattern = '\(.\)'
# pattern = 'freedom'
# pattern = '[a-d]'
# pattern = '(.)'
print(len(re.findall(pattern,text)))

4
